// Code generated by "stringer -type=OpCode isainfo.go"; DO NOT EDIT.

package straightISAv1Info

import "fmt"

const _OpCode_name = "OpNOPOpJOpJROpJALOpBEZOpBNZOpFPBEZOpFPBNZOpADDOpADDiOpSUBOpSUBiOpFTOIOpITOFOpFADDOpFADDiOpFSUBOpFSUBiOpFMULOpFMULiOpFDIVOpFDIViOpSHLOpSHLiOpSHROpSHRiOpANDOpANDiOpOROpORiOpXOROpXORiOpSPADDOpSPADDiOpFPADDOpFPADDiOpLDOpSPLDOpFPLDOpSTOpSPSTOpFPSTOpRPINCOpSLTOpRMOVOpMULOpMULiOpGPADDOpGPADDiOpGPLDOpGPSTOpLDHOpLDHUOpLDQOpLDQUOpLDBOpLDBUOpSTHOpSTQOpSTBOpLUiOpFSLTOpHALTOp_MAX"

var _OpCode_index = [...]uint16{0, 5, 8, 12, 17, 22, 27, 34, 41, 46, 52, 57, 63, 69, 75, 81, 88, 94, 101, 107, 114, 120, 127, 132, 138, 143, 149, 154, 160, 164, 169, 174, 180, 187, 195, 202, 210, 214, 220, 226, 230, 236, 242, 249, 254, 260, 265, 271, 278, 286, 292, 298, 303, 309, 314, 320, 325, 331, 336, 341, 346, 351, 357, 363, 369}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return fmt.Sprintf("OpCode(%d)", i)
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
