// Code generated by "stringer -type=InstType isainfo.go"; DO NOT EDIT.

package straightISAv2Info

import "fmt"

const _InstType_name = "ZeroRegOneRegTwoReg"

var _InstType_index = [...]uint8{0, 7, 13, 19}

func (i InstType) String() string {
	if i < 0 || i >= InstType(len(_InstType_index)-1) {
		return fmt.Sprintf("InstType(%d)", i)
	}
	return _InstType_name[_InstType_index[i]:_InstType_index[i+1]]
}
