// Code generated by "stringer -type=OpCode isainfo.go"; DO NOT EDIT.

package straightISAv1Info

import "strconv"

const _OpCode_name = "OpNOPOpHALTOpSYSCALLOpRETRISCVOpGETRISCVREGOpSETRISCVREGOpJOpJROpJALOpBEZOpBNZOpADDOpADDiOpSUBOpSUBiOpMULOpMULiOpDIVOpDIViOpMODOpMODiOpSLTOpSLTiOpSLTUOpSLTUiOpFTOIOpITOFOpFADDOpFSUBOpFMULOpFDIVOpFSLTOpSHLOpSHLiOpSHROpSHRiOpSHRAOpSHRAiOpANDOpANDiOpOROpORiOpXOROpXORiOpLUiOpAUIPCOpSPADDiOpFPADDiOpGPADDiOpRPINCOpRMOVOpLDOpLDHOpLDHUOpLDQOpLDQUOpLDBOpLDBUOpSTOpSTHOpSTQOpSTBOpSEXTOp_MAX"

var _OpCode_index = [...]uint16{0, 5, 11, 20, 30, 43, 56, 59, 63, 68, 73, 78, 83, 89, 94, 100, 105, 111, 116, 122, 127, 133, 138, 144, 150, 157, 163, 169, 175, 181, 187, 193, 199, 204, 210, 215, 221, 227, 234, 239, 245, 249, 254, 259, 265, 270, 277, 285, 293, 301, 308, 314, 318, 323, 329, 334, 340, 345, 351, 355, 360, 365, 370, 376, 382}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
